// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

namespace CookApps.BM.Newname.Data
{

    /// 공격 아이템 타입
    public enum ITEM_TYPE
    {
        GUN = 0,
        SWORD = 1,
    }

    /// 버프 타입
    public enum BUFF_TYPE
    {
        BUFF_GET_GOLD = 0,
        BUFF_POISON = 1,
        BUFF_HEAL = 2,
        BUFF_KNOCK = 3,
    }

    /// 리워드 타입
    public enum REWARD_TYPE
    {
        REWARD_GOLD = 1,
        REWARD_JEWEL = 2,
        REWARD_ITEM = 3,
    }
}
