// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using System.Linq;
using System.Security.Cryptography;
using System.Text;
using CookApps.SpecData.Generator;

namespace CookApps.BM.Newname.Data
{
    [GeneratorSpecDataResource]
    public static partial class SpecDataResourceLoader
    {
        private static readonly byte[] _key = {117, 73, 96, 115, 113, 53, 84, 107, 79, 42, 107, 83, 106, 64, 100, 119};
    }
}
