// <auto-generated>
// SpecDataGenerator에서 만들어진 파일입니다. 수정하지 마세요.
// Copyright (c) CookApps.
// 이진호(jhlee8@cookapps.com)
// </auto-generated>

using CookApps.SpecData.Generator;

namespace CookApps.BM.Newname.Data
{

    [GeneratorSpecData]
    public partial class Item
    {
        /// 아이디
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 네임키
        public string name_key;
        /// 가격
        public CookApps.Obfuscator.ObfuscatorInt buy_gold;
        /// 아이템 타입
        public global::CookApps.BM.Newname.Data.ITEM_TYPE type;
        /// 디버프
        [GeneratorIdToData(nameof(de_buff), typeof(DeBuff))]
        public CookApps.Obfuscator.ObfuscatorInt de_buff;
        /// 버프
        [GeneratorIdToData(nameof(buff), typeof(Buff))]
        public string buff;
        /// 버프 배열
        [GeneratorIdToData(nameof(arr_buff), typeof(Buff))]
        public string[] arr_buff = global::System.Array.Empty<string>();
        /// 데미지
        public CookApps.Obfuscator.ObfuscatorInt damage;
        /// 랜덤 데미지
        public CookApps.Obfuscator.ObfuscatorInt[] random_damage = global::System.Array.Empty<CookApps.Obfuscator.ObfuscatorInt>();
        /// 랜덤 적용?
        public bool[] apply_random = global::System.Array.Empty<bool>();
        /// string배열 예
        public string[] all_name = global::System.Array.Empty<string>();
        /// 끝 시간
        [GeneratorDateTime(nameof(end_datetime))]
        public string end_datetime;
        /// 시간 배열
        [GeneratorDateTime(nameof(array_datetime))]
        public string[] array_datetime = global::System.Array.Empty<string>();
    }

    [GeneratorSpecData]
    public partial class Buff
    {
        /// 아이디
        [GeneratorId(nameof(id), typeof(string))]
        public string id;
        /// 공격 타입
        public global::CookApps.BM.Newname.Data.BUFF_TYPE type;
        /// 확률
        public CookApps.Obfuscator.ObfuscatorFloat percentage;
        /// 값
        public CookApps.Obfuscator.ObfuscatorInt value;
        /// 랜덤 데미지
        public bool random_damage;
        public CookApps.Obfuscator.ObfuscatorFloat[] random_array = global::System.Array.Empty<CookApps.Obfuscator.ObfuscatorFloat>();
    }

    [GeneratorSpecData]
    public partial class DeBuff
    {
        /// 아이디
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 타입
        public global::CookApps.BM.Newname.Data.BUFF_TYPE type;
        /// 확률
        public CookApps.Obfuscator.ObfuscatorFloat percentage;
        /// 값
        public CookApps.Obfuscator.ObfuscatorInt value;
        /// 랜덤 데미지
        public bool random_damage;
        public CookApps.Obfuscator.ObfuscatorFloat[] random_array = global::System.Array.Empty<CookApps.Obfuscator.ObfuscatorFloat>();
    }

    [GeneratorSpecData]
    [GeneratorSpecDataGroupByFieldName(nameof(reward_group))]
    public partial class Reward
    {
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 보상 그룹 (지급시 해당 필드 이름 사용)
        public string reward_group;
        public global::CookApps.BM.Newname.Data.REWARD_TYPE reward_type;
        public CookApps.Obfuscator.ObfuscatorInt reward_value;
    }

    [GeneratorSpecData]
    public partial class Quest
    {
        [GeneratorId(nameof(id), typeof(CookApps.Obfuscator.ObfuscatorInt))]
        public CookApps.Obfuscator.ObfuscatorInt id;
        /// 퀘스트 조건
        public CookApps.Obfuscator.ObfuscatorInt condition;
        /// 보상시 사용되는 시트 이름
        public string reward_sheet;
        /// 보상 그룹 (지급시 해당 필드, reward_group 이름 사용)
        public string reward_group;
    }
}
